name = "json-fortran-benchmarks"
version = "0.1.0"
license = "BSD-3"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright 2021, Jacob Williams"

[dependencies]
rojff = { git = "https://gitlab.com/everythingfunctional/rojff.git", tag = "f1f20028d7495589980d35101afdf05774cad90d" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran.git", tag = "8.3.0" }
jsonff = {git = "https://gitlab.com/everythingfunctional/jsonff.git", tag = "v3.1.1"}
toml-f = {git = "https://github.com/toml-f/toml-f.git", tag = "v0.3.0"}

[build]
auto-executables = true
auto-examples = true
auto-tests = true


[library]
source-dir = "src"

[install]
library = true