name = "json-fortran-benchmarks"
version = "0.1.0"
license = "BSD-3"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright 2021, Jacob Williams"

[dependencies]
rojff = { git = "https://gitlab.com/everythingfunctional/rojff.git", tag = "f1f20028d7495589980d35101afdf05774cad90d" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran.git", tag = "8.2.5" }
jsonff = {git = "https://gitlab.com/everythingfunctional/jsonff.git", tag = "v3.1.1"}


[[example]]
name="json_fortran_test"
source-dir="app"
main="json_fortran_test.f90"

[[example]]
name="rojff_test"
source-dir="app"
main="rojff_test.f90"

[[example]]
name="read_file_test"
source-dir="app"
main="read_file_test.f90"

[[example]]
name="jsonff_test"
source-dir="app"
main="jsonff_test.f90"
